INSERT INTO CAR_MODEL (ID, MODEL_NAME, PRICE) VALUES (1, 'sedan', 230000);
INSERT INTO CAR_MODEL (ID, MODEL_NAME, PRICE) VALUES (2, 'familiar', 245000);
INSERT INTO CAR_MODEL (ID, MODEL_NAME, PRICE) VALUES (3, 'coupe', 230000);


INSERT INTO PLUS_MISCELLANEOUS (ID, NAME, PRICE) VALUES(1,'techo corredizo',12000);
INSERT INTO PLUS_MISCELLANEOUS (ID, NAME, PRICE) VALUES(2,'aire acondicionado',20000);
INSERT INTO PLUS_MISCELLANEOUS (ID, NAME, PRICE) VALUES(3,'sistema de frenos',14000);
INSERT INTO PLUS_MISCELLANEOUS (ID, NAME, PRICE) VALUES(4,'airbag',7000);
INSERT INTO PLUS_MISCELLANEOUS (ID, NAME, PRICE) VALUES(5,'llantas de aleacion',12000);


INSERT INTO VEHICLE ( ID , MODEL_ID )  VALUES(1,1);
INSERT INTO VEHICLE ( ID , MODEL_ID )  VALUES(2,1);
INSERT INTO VEHICLE ( ID , MODEL_ID )  VALUES(3,1);

INSERT INTO VEHICLE ( ID , MODEL_ID )  VALUES(4,2);
INSERT INTO VEHICLE ( ID , MODEL_ID )  VALUES(5,2);
INSERT INTO VEHICLE ( ID , MODEL_ID )  VALUES(6,2);

INSERT INTO VEHICLE ( ID , MODEL_ID )  VALUES(7,3);
INSERT INTO VEHICLE ( ID , MODEL_ID )  VALUES(8,3);
INSERT INTO VEHICLE ( ID , MODEL_ID )  VALUES(9,3);


INSERT INTO VEHICLE_PLUS_MISCELLANEOUS  ( VEHICLE_ID , PLUS_MISCELLANEOUS_ID ) VALUES (1,1);
INSERT INTO VEHICLE_PLUS_MISCELLANEOUS  ( VEHICLE_ID , PLUS_MISCELLANEOUS_ID ) VALUES (1,2);
INSERT INTO VEHICLE_PLUS_MISCELLANEOUS  ( VEHICLE_ID , PLUS_MISCELLANEOUS_ID ) VALUES (1,3);